# Cloud Build configuration for deploying infrastructure
# Triggered on push to main branch

# TODO: Full implementation tracked in Issue #X

steps:
  # Initialize Terraform
  - name: 'hashicorp/terraform:1.5'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd terraform/environments/${_ENVIRONMENT}
        terraform init -backend-config="bucket=${_TF_STATE_BUCKET}"

  # Validate Terraform
  - name: 'hashicorp/terraform:1.5'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd terraform/environments/${_ENVIRONMENT}
        terraform validate

  # Plan Terraform
  - name: 'hashicorp/terraform:1.5'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd terraform/environments/${_ENVIRONMENT}
        terraform plan -out=tfplan

  # Apply Terraform
  - name: 'hashicorp/terraform:1.5'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd terraform/environments/${_ENVIRONMENT}
        terraform apply -auto-approve tfplan

substitutions:
  _ENVIRONMENT: 'dev'
  _TF_STATE_BUCKET: 'project-beta-terraform-state'

options:
  logging: CLOUD_LOGGING_ONLY
