# GitHub App Secret for ARC Runner Registration
# Uses ExternalSecrets to pull GitHub App credentials from GCP Secret Manager
#
# Prerequisites:
# 1. ExternalSecrets Operator installed
# 2. ClusterSecretStore configured for GCP Secret Manager
# 3. GitHub App secrets exist in GCP Secret Manager:
#    - github-app-id
#    - github-app-installation-id
#    - github-app-private-key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: arc-org-github-secret
  namespace: arc-runners
  labels:
    app.kubernetes.io/component: arc-runners
    app.kubernetes.io/managed-by: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: arc-org-github-secret
    creationPolicy: Owner
  data:
    - secretKey: github_app_id
      remoteRef:
        key: github-app-id
    - secretKey: github_app_installation_id
      remoteRef:
        key: github-app-installation-id
    - secretKey: github_app_private_key
      remoteRef:
        key: github-app-private-key
