# GitHub Token Secret for ARC Runner Registration
# Uses ExternalSecrets to pull from GCP Secret Manager
#
# Prerequisites:
# 1. ExternalSecrets Operator installed
# 2. ClusterSecretStore configured for GCP Secret Manager
# 3. Secret "github-arc-token" exists in GCP Secret Manager
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: arc-org-github-secret
  namespace: arc-runners
  labels:
    app.kubernetes.io/component: arc-runners
    app.kubernetes.io/managed-by: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: arc-org-github-secret
    creationPolicy: Owner
  data:
    - secretKey: github_token
      remoteRef:
        key: github-arc-token
