# ARC Prerequisites Application
# Creates namespaces and ExternalSecrets before other applications
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-prereqs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # Sync before other apps
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Matchpoint-AI/project-beta-runners
    targetRevision: main
    path: argocd/prereqs
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
