apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-runners
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    targetRevision: 0.10.0
    chart: gha-runner-scale-set
    helm:
      releaseName: arc-runners
      values: |
        # GitHub configuration
        githubConfigUrl: https://github.com/Matchpoint-AI
        githubConfigSecret: arc-org-github-secret

        # Runner label (workflows use: runs-on: project-beta-runners)
        runnerScaleSetName: project-beta-runners

        # Autoscaling configuration
        minRunners: 5
        maxRunners: 25

        # Controller reference
        controllerServiceAccount:
          namespace: arc-systems
          name: arc-controller-gha-rs-controller

        # Explicit template for Docker-in-Docker support
        # Using custom template instead of containerMode for full control
        # This enables docker build/push for frontend releases
        template:
          spec:
            initContainers:
              - name: init-dind-externals
                image: ghcr.io/actions/actions-runner:latest
                command: ["cp", "-r", "-v", "/home/runner/externals/.", "/home/runner/tmpDir/"]
                volumeMounts:
                  - name: dind-externals
                    mountPath: /home/runner/tmpDir
            containers:
              - name: runner
                image: ghcr.io/actions/actions-runner:latest
                command: ["/home/runner/run.sh"]
                env:
                  - name: DOCKER_HOST
                    value: unix:///var/run/docker.sock
                  - name: RUNNER_WAIT_FOR_DOCKER_IN_SECONDS
                    value: "120"
                volumeMounts:
                  - name: work
                    mountPath: /home/runner/_work
                  - name: dind-sock
                    mountPath: /var/run
                  - name: dind-externals
                    mountPath: /home/runner/externals
                resources:
                  requests:
                    cpu: "2"
                    memory: 4Gi
                  limits:
                    cpu: "4"
                    memory: 8Gi
              - name: dind
                image: docker:27-dind
                args:
                  - dockerd
                  - --host=unix:///var/run/docker.sock
                  - --group=$(DOCKER_GROUP_GID)
                env:
                  - name: DOCKER_GROUP_GID
                    value: "123"
                securityContext:
                  privileged: true
                volumeMounts:
                  - name: work
                    mountPath: /home/runner/_work
                  - name: dind-sock
                    mountPath: /var/run
                  - name: dind-externals
                    mountPath: /home/runner/externals
                  - name: docker-storage
                    mountPath: /var/lib/docker
                resources:
                  requests:
                    cpu: "1"
                    memory: 2Gi
                  limits:
                    cpu: "2"
                    memory: 4Gi
            volumes:
              - name: work
                emptyDir:
                  sizeLimit: 30Gi
              - name: dind-sock
                emptyDir: {}
              - name: dind-externals
                emptyDir: {}
              - name: docker-storage
                emptyDir:
                  sizeLimit: 30Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: arc-runners
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
