apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-runners
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    targetRevision: 0.9.3
    chart: gha-runner-scale-set
    helm:
      releaseName: arc-runners
      values: |
        # GitHub configuration
        githubConfigUrl: https://github.com/Matchpoint-AI
        githubConfigSecret: arc-org-github-secret

        # Runner label (workflows use: runs-on: project-beta-runners)
        runnerScaleSetName: project-beta-runners

        # Autoscaling configuration
        minRunners: 5
        maxRunners: 25

        # Controller reference
        controllerServiceAccount:
          namespace: arc-systems
          name: arc-controller-gha-rs-controller

        # Use built-in Docker-in-Docker support from the chart
        containerMode:
          type: "dind"
  destination:
    server: https://kubernetes.default.svc
    namespace: arc-runners
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
